using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SSharp.Backend;

/// <summary>
/// Compiles a C# source string entirely in memory (no disk I/O), loads the resulting
/// assembly into an isolated <see cref="AssemblyLoadContext"/>, captures all stdout/stderr
/// output, and invokes the entry point.
/// </summary>
public class EvalBackend
{
    private static string? _runtimeDllPath;

    /// <summary>
    /// Evaluates <paramref name="csharpSource"/> and returns the captured output along
    /// with any compilation errors.
    /// </summary>
    /// <param name="csharpSource">Full C# source text (as generated by <c>CodeGenerator</c>).</param>
    /// <param name="runtimeDllPath">
    ///   Optional explicit path to <c>SSharp.Runtime.dll</c>.
    ///   When <c>null</c>, auto-discovered next to the backend assembly.
    /// </param>
    /// <param name="typeInfo">
    ///   Optional human-readable SSharp type string for the last expression, shown by the REPL.
    /// </param>
    public EvalResult Eval(string csharpSource, string? runtimeDllPath = null, string? typeInfo = null, string? bindingName = null)
    {
        var sw = Stopwatch.StartNew();

        // ── 1. Resolve SSharp.Runtime.dll ────────────────────────────────────
        string? resolvedRuntime = runtimeDllPath ?? _runtimeDllPath ?? ResolveRuntimeDll();
        if (resolvedRuntime == null)
        {
            return new EvalResult(false, string.Empty,
                new[] { "SSharp.Runtime.dll could not be located." },
                sw.ElapsedMilliseconds, typeInfo);
        }
        _runtimeDllPath = resolvedRuntime; // cache for subsequent calls

        // ── 2. Build references ───────────────────────────────────────────────
        var references = BuildReferences(resolvedRuntime);

        // ── 3. Parse + compile ────────────────────────────────────────────────
        var syntaxTree = CSharpSyntaxTree.ParseText(
            csharpSource,
            new CSharpParseOptions(LanguageVersion.Latest));

        var compilation = CSharpCompilation.Create(
            assemblyName: $"SSharp.Eval.{Guid.NewGuid():N}",
            syntaxTrees: new[] { syntaxTree },
            references: references,
            options: new CSharpCompilationOptions(OutputKind.ConsoleApplication)
                .WithOptimizationLevel(OptimizationLevel.Release)
                .WithNullableContextOptions(NullableContextOptions.Enable)
                .WithPlatform(Platform.AnyCpu));

        using var peStream = new MemoryStream();
        var emitResult = compilation.Emit(peStream);

        if (!emitResult.Success)
        {
            var errors = emitResult.Diagnostics
                .Where(d => d.Severity == DiagnosticSeverity.Error)
                .Select(d => d.ToString())
                .ToList();
            return new EvalResult(false, string.Empty, errors, sw.ElapsedMilliseconds, typeInfo);
        }

        peStream.Seek(0, SeekOrigin.Begin);

        // ── 4. Load + execute in isolated context ─────────────────────────────
        var ctx = new CollectibleLoadContext(resolvedRuntime);
        var capturedOutput = new StringBuilder();
        var capturedErrors = new StringBuilder();

        TextWriter originalOut = Console.Out;
        TextWriter originalErr = Console.Error;

        try
        {
            var assembly = ctx.LoadFromStream(peStream);

            // Capture console output
            Console.SetOut(new StringWriter(capturedOutput));
            Console.SetError(new StringWriter(capturedErrors));

            var entryPoint = assembly.EntryPoint;
            if (entryPoint == null)
            {
                // Fallback: look for Program.Main
                var programType = assembly.GetType("SSharp.Generated.Program");
                entryPoint = programType?.GetMethod("Main",
                    BindingFlags.Public | BindingFlags.Static,
                    new[] { typeof(string[]) });
            }

            if (entryPoint == null)
            {
                return new EvalResult(false, string.Empty,
                    new[] { "No entry point found in generated assembly." },
                    sw.ElapsedMilliseconds, typeInfo);
            }

            entryPoint.Invoke(null, new object?[] { Array.Empty<string>() });

            // Retrieve evaluated value of binding if requested
            string? valueString = null;
            if (bindingName != null)
            {
                var programType = assembly.GetType("SSharp.Generated.Program");
                if (programType != null)
                {
                    // EscapeIdentifier may prefix C# keywords with '@', but CLR member
                    // names never include '@', so strip it for reflection lookup.
                    string clrName = bindingName.TrimStart('@');
                    object? valObj = null;
                    bool found = false;

                    var field = programType.GetField(clrName, BindingFlags.Public | BindingFlags.Static);
                    if (field == null)
                        field = programType.GetField($"@{clrName}", BindingFlags.Public | BindingFlags.Static);

                    if (field != null)
                    {
                        valObj = field.GetValue(null);
                        found = true;
                    }
                    else
                    {
                        var prop = programType.GetProperty(clrName, BindingFlags.Public | BindingFlags.Static);
                        if (prop != null)
                        {
                            valObj = prop.GetValue(null);
                            found = true;
                        }
                    }

                    if (found)
                    {
                        valueString = FormatValue(valObj);
                    }
                }
            }

            sw.Stop();
            string output = capturedOutput.ToString();
            string errOutput = capturedErrors.ToString();

            var runtimeErrors = new List<string>();
            if (!string.IsNullOrWhiteSpace(errOutput))
                runtimeErrors.Add(errOutput.TrimEnd());

            return new EvalResult(true, output.TrimEnd('\r', '\n'), runtimeErrors, sw.ElapsedMilliseconds, typeInfo, valueString);
        }
        catch (TargetInvocationException tie)
        {
            sw.Stop();
            Exception inner = tie.InnerException ?? tie;
            if (inner is TypeInitializationException tiex && tiex.InnerException != null)
                inner = tiex.InnerException;
            string msg = inner.Message;
            return new EvalResult(false, capturedOutput.ToString().TrimEnd('\r', '\n'),
                new[] { $"Runtime error: {msg}" }, sw.ElapsedMilliseconds, typeInfo);
        }
        catch (Exception ex)
        {
            sw.Stop();
            return new EvalResult(false, capturedOutput.ToString().TrimEnd('\r', '\n'),
                new[] { $"Unexpected error: {ex.Message}" }, sw.ElapsedMilliseconds, typeInfo);
        }
        finally
        {
            Console.SetOut(originalOut);
            Console.SetError(originalErr);
            ctx.Unload();
        }
    }

    private static string FormatValue(object? obj)
    {
        if (obj == null) return "null";
        if (obj is string s) return $"\"{s}\"";
        if (obj is bool b) return b ? "true" : "false";
        if (obj is double d) return d.ToString(System.Globalization.CultureInfo.InvariantCulture);
        if (obj is float f) return f.ToString(System.Globalization.CultureInfo.InvariantCulture);
        return obj.ToString() ?? "null";
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static List<MetadataReference> BuildReferences(string runtimePath)
    {
        var refs = new List<MetadataReference>();

        var tpaData = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string ?? "";
        foreach (var asmPath in tpaData.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries))
        {
            if (File.Exists(asmPath))
                refs.Add(MetadataReference.CreateFromFile(asmPath));
        }

        if (File.Exists(runtimePath))
            refs.Add(MetadataReference.CreateFromFile(runtimePath));

        return refs;
    }

    private static string? ResolveRuntimeDll()
    {
        string? asmDir = Path.GetDirectoryName(typeof(EvalBackend).Assembly.Location);
        if (asmDir != null)
        {
            string candidate = Path.Combine(asmDir, "SSharp.Runtime.dll");
            if (File.Exists(candidate)) return candidate;
        }

        string? entryDir = Path.GetDirectoryName(Assembly.GetEntryAssembly()?.Location ?? "");
        if (entryDir != null)
        {
            string candidate = Path.Combine(entryDir, "SSharp.Runtime.dll");
            if (File.Exists(candidate)) return candidate;
        }

        return null;
    }

    // ── Collectible AssemblyLoadContext ───────────────────────────────────────

    private sealed class CollectibleLoadContext : AssemblyLoadContext
    {
        private readonly string _runtimePath;

        public CollectibleLoadContext(string runtimePath)
            : base(name: $"SSharpEval-{Guid.NewGuid():N}", isCollectible: true)
        {
            _runtimePath = runtimePath;
        }

        protected override Assembly? Load(AssemblyName assemblyName)
        {
            // Always resolve SSharp.Runtime from the known path
            if (assemblyName.Name == "SSharp.Runtime" && File.Exists(_runtimePath))
                return LoadFromAssemblyPath(_runtimePath);

            // Delegate everything else to the default context
            return null;
        }
    }
}
